/**
 * SEO keyword tiers for South Caravan.
 * Full expanded list is maintained in /additems.txt at repo root.
 */

export const KEYWORD_CATEGORIES = {
  brand: [
    'South Caravan',
    'SouthCaravan',
    'south caravan marketplace',
    'South Caravan B2B platform',
    'South Caravan Uganda',
    'South Caravan Africa',
    'South Caravan global marketplace',
    'South Caravan wholesale',
    'South Caravan suppliers',
  ],
  b2b: [
    'B2B marketplace',
    'business to business platform',
    'B2B trading platform',
    'wholesale marketplace',
    'global wholesale platform',
    'supplier marketplace',
    'buyer supplier platform',
    'online trade platform',
    'digital trading marketplace',
    'B2B ecommerce platform',
    'business marketplace Africa',
    'international B2B marketplace',
    'global B2B network',
    'trade facilitation platform',
    'procurement platform B2B',
    'corporate buyers marketplace',
  ],
  uganda: [
    'Uganda B2B marketplace',
    'Uganda wholesale suppliers',
    'Uganda exporters directory',
    'Uganda import export platform',
    'Uganda business directory',
    'Kampala suppliers',
    'Uganda manufacturers',
    'buy from Uganda',
    'sell to Uganda',
    'Uganda trade platform',
    'Uganda products wholesale',
    'Uganda agriculture exports',
    'Uganda SMEs marketplace',
    'Made in Uganda wholesale',
  ],
  eastAfrica: [
    'East Africa B2B marketplace',
    'East African trade platform',
    'Kenya Uganda Tanzania trade',
    'EAC business network',
    'East Africa exporters',
    'East Africa suppliers directory',
    'East Africa wholesale market',
    'regional trade East Africa',
    'East Africa import export',
    'intra Africa trade platform',
  ],
  africa: [
    'Africa B2B marketplace',
    'African suppliers directory',
    'African exporters platform',
    'African trade hub',
    'pan African marketplace',
    'Africa wholesale platform',
    'African business network',
    'Africa import export',
    'African SMEs platform',
    'Africa digital marketplace',
    'AfCFTA trade platform',
    'African Continental Free Trade Area marketplace',
  ],
  globalTrade: [
    'global trade platform',
    'international suppliers',
    'global exporters directory',
    'import export marketplace',
    'worldwide B2B platform',
    'cross border trade platform',
    'global sourcing platform',
    'international wholesale marketplace',
    'global business network',
    'supply chain marketplace',
    'international trade hub',
  ],
  importExport: [
    'import export business',
    'export goods Africa',
    'import goods Africa',
    'export documentation support',
    'international shipping trade',
    'global logistics marketplace',
    'trade compliance platform',
    'export opportunities Africa',
    'customs clearance support B2B',
  ],
  suppliers: [
    'verified suppliers',
    'trusted suppliers marketplace',
    'wholesale suppliers Africa',
    'manufacturers directory',
    'bulk suppliers platform',
    'product suppliers global',
    'factory direct suppliers',
    'supplier verification platform',
    'vetted exporters Africa',
  ],
  buyers: [
    'bulk buyers platform',
    'international buyers network',
    'wholesale buyers directory',
    'business buyers platform',
    'RFQ buyers platform',
    'tender management buyers',
  ],
  wholesaleBulk: [
    'wholesale',
    'wholesale marketplace',
    'wholesale suppliers Africa',
    'wholesale pricing',
    'wholesale distributor',
    'whole sale',
    'whole sale suppliers',
    'whole sale marketplace',
    'bulk sales',
    'bulk sales platform',
    'bulk purchase',
    'bulk buying',
    'bulk order',
    'bulk orders',
    'bulk ordering',
    'bulk merchandise',
    'bulk goods',
    'bulk products',
    'bulk trade',
    'bulk wholesale',
    'bulk wholesale marketplace',
    'volume sales',
    'volume pricing',
    'large quantity orders',
    'minimum order quantity',
    'MOQ wholesale',
    'buy in bulk Africa',
    'sell in bulk online',
    'distributor pricing',
    'trade pricing B2B',
    'B2B bulk pricing',
    'cash and carry wholesale',
    'factory direct bulk',
    'pallet orders B2B',
    'case pack wholesale',
    'tiered pricing B2B',
    'commodity bulk sales',
    'agricultural bulk sales',
    'bulk import Uganda',
    'bulk export Africa',
  ],
  products: [
    'wholesale products Africa',
    'African goods marketplace',
    'export quality products',
    'bulk goods marketplace',
    'manufactured goods Africa',
    'agricultural products Africa',
    'handmade products Africa',
    'raw materials suppliers',
    'industrial products Africa',
    'commodity trading Africa',
    'wholesale price list Africa',
    'bulk order marketplace',
    'B2B product catalog',
  ],
  industries: [
    'agriculture marketplace Africa',
    'manufacturing suppliers Africa',
    'textile suppliers Africa',
    'construction materials Africa',
    'electronics wholesale Africa',
    'food products wholesale',
    'furniture suppliers Africa',
    'mining products Africa',
    'energy sector suppliers Africa',
    'pharmaceutical wholesale Africa',
    'packaging suppliers Africa',
  ],
  logistics: [
    'global shipping platform',
    'freight forwarding marketplace',
    'cargo logistics Africa',
    'supply chain solutions',
    'international delivery platform',
    'shipping and logistics Africa',
    'warehouse distribution network',
    'transport logistics platform',
    'last mile delivery B2B Africa',
  ],
  payments: [
    'secure B2B payments',
    'international payment gateway',
    'cross border payments Africa',
    'trade payment solutions',
    'escrow payment marketplace',
    'business payment platform',
    'multi currency B2B payments',
  ],
  technology: [
    'AI powered marketplace',
    'smart B2B platform',
    'digital trade ecosystem',
    'online procurement system',
    'cloud B2B platform',
    'mobile B2B marketplace',
    'RFQ automation platform',
    'vendor management software',
  ],
  trust: [
    'verified business network',
    'trusted trade platform',
    'secure marketplace Africa',
    'fraud free B2B platform',
    'business verification system',
    'reliable suppliers network',
    'KYC verified vendors',
  ],
  rfq: [
    'request for quotation platform',
    'RFQ marketplace Africa',
    'online tender platform',
    'bulk quote requests',
    'B2B RFQ management',
    'procurement RFQ Africa',
    'vendor quote comparison',
  ],
  services: [
    'B2B services marketplace',
    'professional services Africa',
    'service provider directory',
    'outsourcing marketplace Africa',
    'business services platform',
  ],
  longTail: [
    'find suppliers Africa',
    'connect buyers and sellers',
    'business expansion Africa',
    'start import export business',
    'grow wholesale business',
    'African trade opportunities',
    'global sourcing Africa',
    'business networking platform',
    'sell wholesale online Africa',
    'source products from Uganda',
    'find exporters in East Africa',
    'B2B marketplace for SMEs',
    'digital export platform Uganda',
    'buy bulk products Uganda',
    'how to find wholesale suppliers Africa',
  ],
} as const

/** Primary keywords for meta tags (curated subset — avoid keyword stuffing). */
export const PRIMARY_META_KEYWORDS: string[] = [
  ...KEYWORD_CATEGORIES.brand.slice(0, 5),
  ...KEYWORD_CATEGORIES.b2b.slice(0, 6),
  ...KEYWORD_CATEGORIES.wholesaleBulk.slice(0, 12),
  ...KEYWORD_CATEGORIES.uganda.slice(0, 5),
  ...KEYWORD_CATEGORIES.africa.slice(0, 5),
  ...KEYWORD_CATEGORIES.globalTrade.slice(0, 4),
  ...KEYWORD_CATEGORIES.suppliers.slice(0, 4),
  ...KEYWORD_CATEGORIES.rfq.slice(0, 3),
  ...KEYWORD_CATEGORIES.longTail.slice(0, 5),
]

/** All keywords flattened (documentation / internal tools). */
export const ALL_KEYWORDS: string[] = Object.values(KEYWORD_CATEGORIES).flat()
